/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package fuzzyowl2.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DATATYPE_DEF = 3;
  /** RegularExpression Id. */
  int MODIFIER_DEF = 4;
  /** RegularExpression Id. */
  int FUZZY_DEF = 5;
  /** RegularExpression Id. */
  int FUZZYOWL2 = 6;
  /** RegularExpression Id. */
  int ONTOLOGY = 7;
  /** RegularExpression Id. */
  int CONCEPT = 8;
  /** RegularExpression Id. */
  int ROLE = 9;
  /** RegularExpression Id. */
  int AXIOM = 10;
  /** RegularExpression Id. */
  int DATATYPE = 11;
  /** RegularExpression Id. */
  int CONCEPT_DEF = 12;
  /** RegularExpression Id. */
  int ROLE_DEF = 13;
  /** RegularExpression Id. */
  int DEGREE_DEF = 14;
  /** RegularExpression Id. */
  int DEGREE_VALUE = 15;
  /** RegularExpression Id. */
  int FUZZYTYPE = 16;
  /** RegularExpression Id. */
  int MODIFIED = 17;
  /** RegularExpression Id. */
  int WEIGHTED = 18;
  /** RegularExpression Id. */
  int FUZZY_NOMINAL = 19;
  /** RegularExpression Id. */
  int INDIVIDUAL = 20;
  /** RegularExpression Id. */
  int WEIGHTED_MAX = 21;
  /** RegularExpression Id. */
  int WEIGHTED_MIN = 22;
  /** RegularExpression Id. */
  int WEIGHTED_SUM = 23;
  /** RegularExpression Id. */
  int CHOQUET = 24;
  /** RegularExpression Id. */
  int SUGENO = 25;
  /** RegularExpression Id. */
  int QUASI_SUGENO = 26;
  /** RegularExpression Id. */
  int MODIFIER = 27;
  /** RegularExpression Id. */
  int BASE = 28;
  /** RegularExpression Id. */
  int OWA = 29;
  /** RegularExpression Id. */
  int QOWA = 30;
  /** RegularExpression Id. */
  int CONCEPTS = 31;
  /** RegularExpression Id. */
  int NAME = 32;
  /** RegularExpression Id. */
  int WEIGHTS = 33;
  /** RegularExpression Id. */
  int WEIGHT = 34;
  /** RegularExpression Id. */
  int QUANTIFIER = 35;
  /** RegularExpression Id. */
  int EOL = 36;
  /** RegularExpression Id. */
  int TYPE = 37;
  /** RegularExpression Id. */
  int LS = 38;
  /** RegularExpression Id. */
  int RS = 39;
  /** RegularExpression Id. */
  int TRI = 40;
  /** RegularExpression Id. */
  int TRAP = 41;
  /** RegularExpression Id. */
  int LINEAR = 42;
  /** RegularExpression Id. */
  int A = 43;
  /** RegularExpression Id. */
  int B = 44;
  /** RegularExpression Id. */
  int C = 45;
  /** RegularExpression Id. */
  int D = 46;
  /** RegularExpression Id. */
  int LOGIC = 47;
  /** RegularExpression Id. */
  int GOEDEL = 48;
  /** RegularExpression Id. */
  int LUKASIEWICZ = 49;
  /** RegularExpression Id. */
  int PRODUCT = 50;
  /** RegularExpression Id. */
  int ZADEH = 51;
  /** RegularExpression Id. */
  int COM1 = 52;
  /** RegularExpression Id. */
  int SIMPLE_COM = 53;
  /** RegularExpression Id. */
  int OP = 54;
  /** RegularExpression Id. */
  int CP = 55;
  /** RegularExpression Id. */
  int OSB = 56;
  /** RegularExpression Id. */
  int CSB = 57;
  /** RegularExpression Id. */
  int OPEN_TAG = 58;
  /** RegularExpression Id. */
  int CLOSE_TAG = 59;
  /** RegularExpression Id. */
  int SLASH = 60;
  /** RegularExpression Id. */
  int EQL = 61;
  /** RegularExpression Id. */
  int LES = 62;
  /** RegularExpression Id. */
  int LEQ = 63;
  /** RegularExpression Id. */
  int GEQ = 64;
  /** RegularExpression Id. */
  int GRE = 65;
  /** RegularExpression Id. */
  int IDENTIFIER = 66;
  /** RegularExpression Id. */
  int NUMBER = 67;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"Datatype\"",
    "\"Modifier\"",
    "\"FuzzyLogic\"",
    "\"fuzzyOwl2\"",
    "\"ontology\"",
    "\"concept\"",
    "\"role\"",
    "\"axiom\"",
    "\"datatype\"",
    "\"Concept\"",
    "\"Role\"",
    "\"Degree\"",
    "\"value\"",
    "\"fuzzyType\"",
    "\"modified\"",
    "\"weighted\"",
    "\"nominal\"",
    "\"individual\"",
    "\"weightedMaximum\"",
    "\"weightedMinimum\"",
    "\"weightedSum\"",
    "\"choquet\"",
    "\"sugeno\"",
    "\"quasiSugeno\"",
    "\"modifier\"",
    "\"base\"",
    "\"owa\"",
    "\"qowa\"",
    "\"Names\"",
    "\"Name\"",
    "\"Weights\"",
    "\"Weight\"",
    "\"quantifier\"",
    "<EOL>",
    "\"type\"",
    "\"leftshoulder\"",
    "\"rightshoulder\"",
    "\"triangular\"",
    "\"trapezoidal\"",
    "\"linear\"",
    "\"a\"",
    "\"b\"",
    "\"c\"",
    "\"d\"",
    "\"logic\"",
    "\"goedel\"",
    "\"lukasiewicz\"",
    "\"product\"",
    "\"zadeh\"",
    "\"\\\\\\\"\"",
    "\"\\\"\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"<\"",
    "\">\"",
    "\"/\"",
    "\"=\"",
    "\"les\"",
    "\"leq\"",
    "\"geq\"",
    "\"gre\"",
    "<IDENTIFIER>",
    "<NUMBER>",
  };

}
