/* Generated By:JavaCC: Do not edit this line. ParserTokenManager.java */
package fuzzyowl2.parser;

/** Token Manager. */
public class ParserTokenManager implements ParserConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x780011000d00L) != 0L)
            return 4;
         if ((active0 & 0xc00f87efeefff2f8L) != 0L || (active1 & 0x3L) != 0L)
         {
            jjmatchedKind = 66;
            return 4;
         }
         return -1;
      case 1:
         if ((active0 & 0xc00f87effffffff8L) != 0L || (active1 & 0x3L) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 1;
            return 4;
         }
         return -1;
      case 2:
         if ((active0 & 0xc000000020000000L) != 0L || (active1 & 0x3L) != 0L)
            return 4;
         if ((active0 & 0xf87efdffffff8L) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 2;
            return 4;
         }
         return -1;
      case 3:
         if ((active0 & 0x21d0002200L) != 0L)
            return 4;
         if ((active0 & 0xf87ce0fffddf8L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 66;
               jjmatchedPos = 3;
            }
            return 4;
         }
         return -1;
      case 4:
         if ((active0 & 0x8800080008400L) != 0L)
            return 4;
         if ((active0 & 0x707ce0fff59f8L) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 4;
            return 4;
         }
         return -1;
      case 5:
         if ((active0 & 0x1040602004000L) != 0L)
            return 4;
         if ((active0 & 0x603c80dff19f8L) != 0L)
         {
            if (jjmatchedPos != 5)
            {
               jjmatchedKind = 66;
               jjmatchedPos = 5;
            }
            return 4;
         }
         return -1;
      case 6:
         if ((active0 & 0x4000201081100L) != 0L)
            return 4;
         if ((active0 & 0x203c80cf708f8L) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 6;
            return 4;
         }
         return -1;
      case 7:
         if ((active0 & 0x8e60898L) != 0L)
            return 4;
         if ((active0 & 0x203c804110060L) != 0L)
         {
            if (jjmatchedPos != 7)
            {
               jjmatchedKind = 66;
               jjmatchedPos = 7;
            }
            return 4;
         }
         return -1;
      case 8:
         if ((active0 & 0x10040L) != 0L)
            return 4;
         if ((active0 & 0x203c804f00020L) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 8;
            return 4;
         }
         return -1;
      case 9:
         if ((active0 & 0x10800100020L) != 0L)
            return 4;
         if ((active0 & 0x202c004e00000L) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 9;
            return 4;
         }
         return -1;
      case 10:
         if ((active0 & 0xc000600000L) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 10;
            return 4;
         }
         if ((active0 & 0x2020004800000L) != 0L)
            return 4;
         return -1;
      case 11:
         if ((active0 & 0x4000000000L) != 0L)
            return 4;
         if ((active0 & 0x8000600000L) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 11;
            return 4;
         }
         return -1;
      case 12:
         if ((active0 & 0x8000000000L) != 0L)
            return 4;
         if ((active0 & 0x600000L) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 12;
            return 4;
         }
         return -1;
      case 13:
         if ((active0 & 0x600000L) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 13;
            return 4;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 34:
         return jjStopAtPos(0, 53);
      case 40:
         return jjStopAtPos(0, 54);
      case 41:
         return jjStopAtPos(0, 55);
      case 47:
         return jjStopAtPos(0, 60);
      case 60:
         return jjStopAtPos(0, 58);
      case 61:
         return jjStopAtPos(0, 61);
      case 62:
         return jjStopAtPos(0, 59);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x1000L, 0x0L);
      case 68:
         return jjMoveStringLiteralDfa1_0(0x4008L, 0x0L);
      case 70:
         return jjMoveStringLiteralDfa1_0(0x20L, 0x0L);
      case 77:
         return jjMoveStringLiteralDfa1_0(0x10L, 0x0L);
      case 78:
         return jjMoveStringLiteralDfa1_0(0x180000000L, 0x0L);
      case 82:
         return jjMoveStringLiteralDfa1_0(0x2000L, 0x0L);
      case 87:
         return jjMoveStringLiteralDfa1_0(0x600000000L, 0x0L);
      case 91:
         return jjStopAtPos(0, 56);
      case 92:
         return jjMoveStringLiteralDfa1_0(0x10000000000000L, 0x0L);
      case 93:
         return jjStopAtPos(0, 57);
      case 97:
         jjmatchedKind = 43;
         return jjMoveStringLiteralDfa1_0(0x400L, 0x0L);
      case 98:
         jjmatchedKind = 44;
         return jjMoveStringLiteralDfa1_0(0x10000000L, 0x0L);
      case 99:
         jjmatchedKind = 45;
         return jjMoveStringLiteralDfa1_0(0x1000100L, 0x0L);
      case 100:
         jjmatchedKind = 46;
         return jjMoveStringLiteralDfa1_0(0x800L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x10040L, 0x0L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x1000000000000L, 0x3L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x100000L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0xc002844000000000L, 0x0L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x8020000L, 0x0L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x80000L, 0x0L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x20000080L, 0x0L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x4000000000000L, 0x0L);
      case 113:
         return jjMoveStringLiteralDfa1_0(0x844000000L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x8000000200L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x2000000L, 0x0L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x32000000000L, 0x0L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x8000L, 0x0L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0xe40000L, 0x0L);
      case 122:
         return jjMoveStringLiteralDfa1_0(0x8000000000000L, 0x0L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 34:
         if ((active0 & 0x10000000000000L) != 0L)
            return jjStopAtPos(1, 52);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000190008808L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0xc000004600e44000L, active1, 0x1L);
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x48000000000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x100080L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x18000480a3310L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x4030000000000L, active1, 0x2L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000806010060L, active1, 0L);
      case 119:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000L, active1, 0L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x400L, active1, 0L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 97:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(2, 29, 4);
         return jjMoveStringLiteralDfa3_0(active0, 0x20804000000L, active1, 0L);
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000008120010L, active1, 0L);
      case 101:
         if ((active1 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(2, 65, 4);
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000000L, active1, 0L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000L, active1, 0L);
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0x808002004000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x10600e40400L, active1, 0L);
      case 107:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0xa200L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x180080000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000001100L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000001000000L, active1, 0L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000L, active1, 0L);
      case 113:
         if ((active0 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 63, 4);
         else if ((active1 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(2, 64, 4);
         break;
      case 115:
         if ((active0 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 62, 4);
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x888L, active1, 0L);
      case 119:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000L, active1, 0L);
      case 122:
         return jjMoveStringLiteralDfa3_0(active0, 0x10060L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, 0L);
      return 3;
   }
   switch(curChar)
   {
      case 97:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(3, 30, 4);
         return jjMoveStringLiteralDfa4_0(active0, 0x2010000000808L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x1100L);
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x5000000000000L);
      case 101:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(3, 9, 4);
         else if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(3, 13, 4);
         else if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(3, 28, 4);
         else if ((active0 & 0x100000000L) != 0L)
         {
            jjmatchedKind = 32;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 37, 4);
         return jjMoveStringLiteralDfa4_0(active0, 0x8040082000000L);
      case 103:
         return jjMoveStringLiteralDfa4_0(active0, 0x600e40000L);
      case 104:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000000L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000081a0010L);
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x480L);
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000000L);
      case 113:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000000L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000L);
      case 122:
         return jjMoveStringLiteralDfa4_0(active0, 0x10060L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, 0L);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, 0L);
      return 4;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000000L);
      case 99:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 47, 4);
         break;
      case 101:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(4, 15, 4);
         return jjMoveStringLiteralDfa5_0(active0, 0x1020000005100L);
      case 102:
         return jjMoveStringLiteralDfa5_0(active0, 0x8020010L);
      case 104:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 51, 4);
         return jjMoveStringLiteralDfa5_0(active0, 0x600e40000L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000L);
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x80L);
      case 109:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(4, 10, 4);
         break;
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x10002080000L);
      case 115:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(4, 31, 4);
         return jjMoveStringLiteralDfa5_0(active0, 0x2004000000000L);
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x8800000808L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000001000000L);
      case 118:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000L);
      case 121:
         return jjMoveStringLiteralDfa5_0(active0, 0x10060L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, 0L);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, 0L);
      return 5;
   }
   switch(curChar)
   {
      case 76:
         return jjMoveStringLiteralDfa6_0(active0, 0x20L);
      case 79:
         return jjMoveStringLiteralDfa6_0(active0, 0x40L);
      case 83:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000L);
      case 84:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000L);
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000L);
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000000000L);
      case 101:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(5, 14, 4);
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000L);
      case 103:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000000L);
      case 104:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000000L);
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000808120010L);
      case 108:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 48, 4);
         break;
      case 111:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(5, 25, 4);
         return jjMoveStringLiteralDfa6_0(active0, 0x80L);
      case 112:
         return jjMoveStringLiteralDfa6_0(active0, 0x1100L);
      case 114:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 42, 4);
         break;
      case 115:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000000000L);
      case 116:
         if ((active0 & 0x400000000L) != 0L)
         {
            jjmatchedKind = 34;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x200e40000L);
      case 121:
         return jjMoveStringLiteralDfa6_0(active0, 0x808L);
      case 122:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, 0L);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, 0L);
      return 6;
   }
   switch(curChar)
   {
      case 100:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000L);
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000008e60010L);
      case 102:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000000L);
      case 103:
         return jjMoveStringLiteralDfa7_0(active0, 0x80L);
      case 104:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000000L);
      case 108:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(6, 19, 4);
         break;
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x24000000020L);
      case 112:
         return jjMoveStringLiteralDfa7_0(active0, 0x808L);
      case 115:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(6, 33, 4);
         break;
      case 116:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(6, 8, 4);
         else if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(6, 12, 4);
         else if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(6, 24, 4);
         else if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 50, 4);
         break;
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x10004000000L);
      case 119:
         return jjMoveStringLiteralDfa7_0(active0, 0x40L);
      case 121:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, 0L);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, 0L);
      return 7;
   }
   switch(curChar)
   {
      case 100:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(7, 17, 4);
         else if ((active0 & 0x40000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 7;
         }
         return jjMoveStringLiteralDfa8_0(active0, 0xe00000L);
      case 101:
         if ((active0 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(7, 3, 4);
         else if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(7, 11, 4);
         break;
      case 103:
         return jjMoveStringLiteralDfa8_0(active0, 0x4000020L);
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x20800000000L);
      case 108:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000000040L);
      case 111:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000000000L);
      case 112:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000L);
      case 114:
         if ((active0 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(7, 4, 4);
         else if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(7, 27, 4);
         break;
      case 117:
         return jjMoveStringLiteralDfa8_0(active0, 0x4000100000L);
      case 119:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000000000000L);
      case 121:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(7, 7, 4);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0, 0L);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, 0L);
      return 8;
   }
   switch(curChar)
   {
      case 50:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(8, 6, 4);
         break;
      case 77:
         return jjMoveStringLiteralDfa9_0(active0, 0x600000L);
      case 83:
         return jjMoveStringLiteralDfa9_0(active0, 0x800000L);
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0x10000100000L);
      case 100:
         return jjMoveStringLiteralDfa9_0(active0, 0x20000000000L);
      case 101:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(8, 16, 4);
         return jjMoveStringLiteralDfa9_0(active0, 0x804000000L);
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x2000000000020L);
      case 108:
         return jjMoveStringLiteralDfa9_0(active0, 0x4000000000L);
      case 117:
         return jjMoveStringLiteralDfa9_0(active0, 0x8000000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, 0L);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, 0L);
      return 9;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa10_0(active0, 0x20000200000L);
      case 99:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(9, 5, 4);
         return jjMoveStringLiteralDfa10_0(active0, 0x2000000000000L);
      case 100:
         return jjMoveStringLiteralDfa10_0(active0, 0x4000000000L);
      case 105:
         return jjMoveStringLiteralDfa10_0(active0, 0x400000L);
      case 108:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(9, 20, 4);
         return jjMoveStringLiteralDfa10_0(active0, 0x8000000000L);
      case 110:
         return jjMoveStringLiteralDfa10_0(active0, 0x4000000L);
      case 114:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(9, 35, 4);
         else if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 40, 4);
         break;
      case 117:
         return jjMoveStringLiteralDfa10_0(active0, 0x800000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0, 0L);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, 0L);
      return 10;
   }
   switch(curChar)
   {
      case 100:
         return jjMoveStringLiteralDfa11_0(active0, 0x8000000000L);
      case 101:
         return jjMoveStringLiteralDfa11_0(active0, 0x4000000000L);
      case 108:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 41, 4);
         break;
      case 109:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(10, 23, 4);
         break;
      case 110:
         return jjMoveStringLiteralDfa11_0(active0, 0x400000L);
      case 111:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(10, 26, 4);
         break;
      case 120:
         return jjMoveStringLiteralDfa11_0(active0, 0x200000L);
      case 122:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 49, 4);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, active0, 0L);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0, 0L);
      return 11;
   }
   switch(curChar)
   {
      case 101:
         return jjMoveStringLiteralDfa12_0(active0, 0x8000000000L);
      case 105:
         return jjMoveStringLiteralDfa12_0(active0, 0x600000L);
      case 114:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(11, 38, 4);
         break;
      default :
         break;
   }
   return jjStartNfa_0(10, active0, 0L);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0, 0L);
      return 12;
   }
   switch(curChar)
   {
      case 109:
         return jjMoveStringLiteralDfa13_0(active0, 0x600000L);
      case 114:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(12, 39, 4);
         break;
      default :
         break;
   }
   return jjStartNfa_0(11, active0, 0L);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0, 0L);
      return 13;
   }
   switch(curChar)
   {
      case 117:
         return jjMoveStringLiteralDfa14_0(active0, 0x600000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0, 0L);
}
private int jjMoveStringLiteralDfa14_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0, 0L);
      return 14;
   }
   switch(curChar)
   {
      case 109:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(14, 21, 4);
         else if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(14, 22, 4);
         break;
      default :
         break;
   }
   return jjStartNfa_0(13, active0, 0L);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 9;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 67)
                        kind = 67;
                     jjCheckNAddStates(0, 2);
                  }
                  else if ((0x2400L & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                  }
                  else if (curChar == 46)
                     jjCheckNAdd(7);
                  else if (curChar == 45)
                     jjCheckNAddTwoStates(6, 8);
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 1:
                  if (curChar == 10 && kind > 36)
                     kind = 36;
                  break;
               case 2:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 4:
                  if ((0x3ff600000000000L & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 5:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(6, 8);
                  break;
               case 6:
                  if (curChar == 46)
                     jjCheckNAdd(7);
                  break;
               case 7:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAdd(7);
                  break;
               case 8:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(0, 2);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  jjCheckNAdd(4);
                  break;
               case 4:
                  if ((0x7fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  jjCheckNAdd(4);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 9 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   6, 7, 8, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, "\104\141\164\141\164\171\160\145", 
"\115\157\144\151\146\151\145\162", "\106\165\172\172\171\114\157\147\151\143", 
"\146\165\172\172\171\117\167\154\62", "\157\156\164\157\154\157\147\171", "\143\157\156\143\145\160\164", 
"\162\157\154\145", "\141\170\151\157\155", "\144\141\164\141\164\171\160\145", 
"\103\157\156\143\145\160\164", "\122\157\154\145", "\104\145\147\162\145\145", "\166\141\154\165\145", 
"\146\165\172\172\171\124\171\160\145", "\155\157\144\151\146\151\145\144", "\167\145\151\147\150\164\145\144", 
"\156\157\155\151\156\141\154", "\151\156\144\151\166\151\144\165\141\154", 
"\167\145\151\147\150\164\145\144\115\141\170\151\155\165\155", "\167\145\151\147\150\164\145\144\115\151\156\151\155\165\155", 
"\167\145\151\147\150\164\145\144\123\165\155", "\143\150\157\161\165\145\164", "\163\165\147\145\156\157", 
"\161\165\141\163\151\123\165\147\145\156\157", "\155\157\144\151\146\151\145\162", "\142\141\163\145", "\157\167\141", 
"\161\157\167\141", "\116\141\155\145\163", "\116\141\155\145", "\127\145\151\147\150\164\163", 
"\127\145\151\147\150\164", "\161\165\141\156\164\151\146\151\145\162", null, "\164\171\160\145", 
"\154\145\146\164\163\150\157\165\154\144\145\162", "\162\151\147\150\164\163\150\157\165\154\144\145\162", 
"\164\162\151\141\156\147\165\154\141\162", "\164\162\141\160\145\172\157\151\144\141\154", "\154\151\156\145\141\162", 
"\141", "\142", "\143", "\144", "\154\157\147\151\143", "\147\157\145\144\145\154", 
"\154\165\153\141\163\151\145\167\151\143\172", "\160\162\157\144\165\143\164", "\172\141\144\145\150", "\134\42", "\42", 
"\50", "\51", "\133", "\135", "\74", "\76", "\57", "\75", "\154\145\163", 
"\154\145\161", "\147\145\161", "\147\162\145", null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xfffffffffffffff9L, 0xfL, 
};
static final long[] jjtoSkip = {
   0x6L, 0x0L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[9];
private final int[] jjstateSet = new int[18];
protected char curChar;
/** Constructor. */
public ParserTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public ParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 9; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100000200L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}

private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
